name: test
on: push

jobs:
  build:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make -j2 -C test
      - run: make -C example/gillespie
      - run: make -C example/random_network
